// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd1akZ8cM3H2qTulpgMHa5uxVnDoz3dOY',
    appId: '1:373337511878:android:159b5b95e632c4de18c4c7',
    messagingSenderId: '373337511878',
    projectId: 'lums-photo-2026',
    storageBucket: 'lums-photo-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCa5xOLk7OBITB3JbqdCMrxyx7mKE9goM',
    appId: '1:373337511878:ios:56d31ffa8d0ff81b18c4c7',
    messagingSenderId: '373337511878',
    projectId: 'lums-photo-2026',
    storageBucket: 'lums-photo-2026.firebasestorage.app',
    iosBundleId: 'com.example.lums',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ZqxJ40MN__K-09vkqt52Ibcve4vvcN8',
    appId: '1:373337511878:web:d435f6b4269febf618c4c7',
    messagingSenderId: '373337511878',
    projectId: 'lums-photo-2026',
    authDomain: 'lums-photo-2026.firebaseapp.com',
    storageBucket: 'lums-photo-2026.firebasestorage.app',
    measurementId: 'G-0XLL3EGYPN',
  );
}
