import 'package:flutter/widgets.dart';
import 'package:firebase_core/firebase_core.dart'; // Add this
import 'firebase_options.dart'; // This file was generated by your flutterfire configure command
import 'app.dart';

void main() async { // 1. Change to async
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase before running the app
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const SnapGatherApp());
}